import { faL } from "@fortawesome/free-solid-svg-icons";

export default [
  {
    id: 1,
    firstName: "Andres",
    lastName: "Gonzalez",
    phoneNumber: 381 - 617 - 8475,
    pictureUrl: "https://image.ibb.co/k0wVTm/profile_pic.jpg",
    message: {
      lastMessage: "Hi there",
      lastMessageTimestamp: "13:50",
      isLastMessageRecieved: true,
      isLastMessageRead: false,
    },
    isArchived: true,
  },
  {
    id: 2,
    firstName: "Rocio",
    lastName: "Valdivieso",
    phoneNumber: 381 - 479 - 8834,
    pictureUrl: "https://image.ibb.co/cA2oOb/alex_1.jpg",
    message: {
      lastMessage: "I love you",
      lastMessageTimestamp: "2:10",
      isLastMessageRecieved: true,
      isLastMessageRead: true,
    },
    isArchived: false,
  },
  {
    id: 3,
    firstName: "Bob",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/gSyTOb/bob_1.jpg",
    message: {
      lastMessageTimestamp: "12:30 AM",
      lastMessage: "Alright",
      isLastMessageRecieved: false,
      isLastMessageRead: false,
    },
    isArchived: true,
  },
  {
    id: 4,
    firstName: "Luke",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/jOzeUG/luke_1.jpg",
    message: {
      lastMessageTimestamp: "4:12 PM",
      lastMessage: "I will look into it",
      isLastMessageRecieved: true,
      isLastMessageRead: false,
    },
    isArchived: false,
  },
  {
    id: 5,
    firstName: "Bane",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/cBZPww/bane_1.jpg",
    message: {
      lastMessageTimestamp: "7:53 PM",
      lastMessage: "Exactly my point!",
      isLastMessageRecieved: false,
      isLastMessageRead: true,
    },
    isArchived: false,
  },
  {
    id: 6,
    firstName: "Darth Vader",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/j4Ov3b/darth_vader_1.png",
    message: {
      lastMessageTimestamp: "1:09 PM",
      lastMessage: "Not quite the same.",
      isLastMessageRecieved: false,
      isLastMessageRead: false,
    },
    isArchived: false,
  },
  {
    id: 7,
    firstName: "Zach",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/b4kxGw/zach_1.jpg",
    message: {
      lastMessageTimestamp: "Yesterday",
      lastMessage: "I thought that the event was over long ago",
      isLastMessageRecieved: true,
      isLastMessageRead: true,
    },
    isArchived: false,
  },
  {
    id: 8,
    firstName: "Katie",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/eLVWbw/katie_1.jpg",
    message: {
      lastMessageTimestamp: "Yesterday",
      lastMessage: "nothing",
      isLastMessageRecieved: true,
      isLastMessageRead: false,
    },
    isArchived: false,
  },
  {
    id: 9,
    firstName: "Chloe",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/ncAa3b/chloe_1.jpg",
    message: {
      lastMessageTimestamp: "Wednesday",
      lastMessage: "sure i'll take it from you",
      isLastMessageRecieved: false,
      isLastMessageRead: false,
    },
    isArchived: false,
  },
  {
    id: 10,
    firstName: "Kennith",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/fQKPww/kennith_1.jpg",
    message: {
      lastMessageTimestamp: "Wednesday",
      lastMessage: "Take care, bye",
      isLastMessageRecieved: false,
      isLastMessageRead: true,
    },
    isArchived: false,
  },
  {
    id: 11,
    firstName: "Tara",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/dM6hib/tara_1.jpg",
    message: {
      lastMessageTimestamp: "Monday",
      lastMessage: "Not today",
      isLastMessageRecieved: false,
      isLastMessageRead: true,
    },
    isArchived: false,
  },
  {
    id: 12,
    firstName: "Gary",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/gsF8Ob/gary_1.jpg",
    message: {
      lastMessageTimestamp: "Sunday",
      lastMessage: "Whatever works for you!",
      isLastMessageRecieved: true,
      isLastMessageRead: true,
    },
    isArchived: false,
  },
  {
    id: 13,
    firstName: "Zoey",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/nd0Wbw/zoey_1.jpg",
    message: {
      lastMessageTimestamp: "8/12/2017",
      lastMessage: "Will get in touch",
      isLastMessageRecieved: true,
      isLastMessageRead: false,
    },
    isArchived: false,
  },
  {
    id: 14,
    firstName: "Ash",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/iasYpG/ash_1.jpg",
    message: {
      lastMessageTimestamp: "6/12/2017",
      lastMessage: "Ok",
      isLastMessageRecieved: true,
      isLastMessageRead: true,
    },
    isArchived: false,
  },
  {
    id: 15,
    firstName: "Zen",
    lastName: "",
    phoneNumber: "",
    pictureUrl: "https://image.ibb.co/eeqWbw/zen_1.jpg",
    message: {
      lastMessageTimestamp: "19/11/2017",
      lastMessage: "Lol",
      isLastMessageRecieved: true,
      isLastMessageRead: false,
    },
    isArchived: false,
  },
];
